#포트설정
server:
  port: '8081'

#JSP설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    post: '587'
    username: iamstudybox00@gmail.com
    password: vxji kgen kaoc qheh
    properties:
      mail:
        debug: 'true'
        smtp: 
          connectiontimeout: '5000'
          auth: 'false'
          starttls:
            enable: 'true'
            required: 'true'
